name: Build and Deploy to Nuget

env:
  APP: "Netcorext.Extensions.DependencyInjection"
  APP_ABSTRACTIONS: "Netcorext.Extensions.DependencyInjection.Abstractions"
  APP_ASPNETCORE: "Netcorext.Extensions.DependencyInjection.AspNetCore"

on:
  push:
    branches: [ main, dev ]

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
    steps:
      - uses: netcorext/dotnet-build-package-action@dev
        name: Build Package
        id: build
        with:
          app: ${{ env.APP }}
  BuildAbstractions:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
    steps:
      - uses: netcorext/dotnet-build-package-action@dev
        name: Build Package
        id: build
        with:
          app: ${{ env.APP_ABSTRACTIONS }}
  BuildAspNetCore:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
    steps:
      - uses: netcorext/dotnet-build-package-action@dev
        name: Build Package
        id: build
        with:
          app: ${{ env.APP_ASPNETCORE }}
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: netcorext/push-nuget-package-action@dev
        name: Push Package
        with:
          artifact: ${{ needs.Build.outputs.artifact }}
          nuget-api-url: ${{ secrets.NUGET_API_URL }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
  DeployAbstractions:
    runs-on: ubuntu-latest
    needs: BuildAbstractions
    steps:
      - uses: netcorext/push-nuget-package-action@dev
        name: Push Package
        with:
          artifact: ${{ needs.BuildAbstractions.outputs.artifact }}
          nuget-api-url: ${{ secrets.NUGET_API_URL }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
  DeployAspNetCore:
    runs-on: ubuntu-latest
    needs: BuildAspNetCore
    steps:
      - uses: netcorext/push-nuget-package-action@dev
        name: Push Package
        with:
          artifact: ${{ needs.BuildAspNetCore.outputs.artifact }}
          nuget-api-url: ${{ secrets.NUGET_API_URL }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}